import contextlib, io, importlib.util, itertools
import numpy as np
import pandas as pd
buf=io.StringIO()
with contextlib.redirect_stdout(buf):
    spec=importlib.util.spec_from_file_location('b','/mnt/data/test_varphylo2.py')
    b=importlib.util.module_from_spec(spec); spec.loader.exec_module(b)
pi=b.pi; Pt=b.Pt; P2=b.P2; P4=b.P4; cb=b.cb; mb=b.mb
LP=b.LP; mcc=b.mcc; mass=b.mass; obbt=b.obbt
leaf_parents=b.leaf_parents; exact_best=b.exact_best

def routeprod_full(lp,w,a,x,lx,ux):
    lp.ge({w:1,a:-lx},0)
    lp.ge({w:1,x:-1,a:-ux},-ux)
    lp.le({w:1,a:-ux},0)
    lp.le({w:1,x:-1,a:-lx},-lx)

def add_subset_hulls(lp,A,B,Z,which=(2,3,4)):
    # For any subset S, its average diagonal product E_S[A_i B_i]
    # obeys the McCormick/Frechet envelope generated by E_S[A_i], E_S[B_i]
    # and pointwise ranges over S.  This couples states without topology integrality.
    states=range(4)
    for size in which:
        for S in itertools.combinations(states,size):
            la=min(lp.bounds[A[i]][0] for i in S); ua=max(lp.bounds[A[i]][1] for i in S)
            lb=min(lp.bounds[B[i]][0] for i in S); ub=max(lp.bounds[B[i]][1] for i in S)
            # Zsum >= la*Bsum + lb*Asum - m*la*lb
            d={Z[i]:1 for i in S}
            for i in S:
                d[B[i]]=d.get(B[i],0)-la; d[A[i]]=d.get(A[i],0)-lb
            lp.ge(d,-size*la*lb)
            # Zsum >= ua*Bsum + ub*Asum - m*ua*ub
            d={Z[i]:1 for i in S}
            for i in S:
                d[B[i]]=d.get(B[i],0)-ua; d[A[i]]=d.get(A[i],0)-ub
            lp.ge(d,-size*ua*ub)
            # Zsum <= ua*Bsum + lb*Asum - m*ua*lb
            d={Z[i]:1 for i in S}
            for i in S:
                d[B[i]]=d.get(B[i],0)-ua; d[A[i]]=d.get(A[i],0)-lb
            lp.le(d,-size*ua*lb)
            # Zsum <= la*Bsum + ub*Asum - m*la*ub
            d={Z[i]:1 for i in S}
            for i in S:
                d[B[i]]=d.get(B[i],0)-la; d[A[i]]=d.get(A[i],0)-ub
            lp.le(d,-size*la*ub)

def add_cross_product_rlt(lp,A,B,Z,qA,qB,prefix,ratioA=None,ratioB=None):
    W=[[None]*4 for _ in range(4)]
    for i in range(4):
        la,ua=lp.bounds[A[i]]
        for j in range(4):
            lb,ub=lp.bounds[B[j]]
            w=lp.var(f'{prefix}_W_{i}_{j}',la*lb,ua*ub)
            mcc(lp,w,A[i],B[j],la,ua,lb,ub);W[i][j]=w
    for i in range(4):lp.eq({W[i][i]:1,Z[i]:-1},0)
    lqa,uqa=lp.bounds[qA];lqb,uqb=lp.bounds[qB]
    for i in range(4):
        la,ua=lp.bounds[A[i]];t=lp.var(f'{prefix}_row_{i}',la*lqb,ua*uqb);mcc(lp,t,A[i],qB,la,ua,lqb,uqb)
        d={t:-1}
        for j in range(4):d[W[i][j]]=d.get(W[i][j],0)+.25
        lp.eq(d,0)
    for j in range(4):
        lb,ub=lp.bounds[B[j]];t=lp.var(f'{prefix}_col_{j}',lb*lqa,ub*uqa);mcc(lp,t,B[j],qA,lb,ub,lqa,uqa)
        d={t:-1}
        for i in range(4):d[W[i][j]]=d.get(W[i][j],0)+.25
        lp.eq(d,0)
    r=lp.var(f'{prefix}_massprod',lqa*lqb,uqa*uqb);mcc(lp,r,qA,qB,lqa,uqa,lqb,uqb)
    d={r:-1}
    for i in range(4):
        for j in range(4):d[W[i][j]]=d.get(W[i][j],0)+.0625
    lp.eq(d,0)
    if ratioA is not None:
        for i in range(4):
            for k in range(i+1,4):
                rlo,rhi=ratioA[(i,k)]
                for j in range(4):
                    lp.ge({W[i][j]:1,W[k][j]:-rlo},0);lp.le({W[i][j]:1,W[k][j]:-rhi},0)
    if ratioB is not None:
        for j in range(4):
            for k in range(j+1,4):
                rlo,rhi=ratioB[(j,k)]
                for i in range(4):
                    lp.ge({W[i][j]:1,W[i][k]:-rlo},0);lp.le({W[i][j]:1,W[i][k]:-rhi},0)
    return W

def build(pat,use_route=False,use_subset=False,use_cross=False,exact_bottom=False,use_dir=False,basepair_bottom=False,upper_pair_rlt=False):
    lm=np.array([Pt[:,x] for x in pat]); lp=LP()
    # leaves -> count2 slots
    slots2=[(p,s) for p in range(4) for s in range(2)]; y={}
    for e in range(8):
        ks=[k for k,(p,s) in enumerate(slots2) if p in leaf_parents[e]]
        for k in ks:y[e,k]=lp.var(f'y1_{e}_{k}',0,1)
        lp.eq({y[e,k]:1 for k in ks},1)
    for k in range(8):lp.eq({y[e,k]:1 for e in range(8) if (e,k) in y},1)
    s2=[]
    for k in range(8):
        vec=[]
        for i in range(4):
            es=[e for e in range(8) if (e,k) in y]; vals=[lm[e,i] for e in es]
            v=lp.var(f's2_{k}_{i}',min(vals),max(vals));d={v:1}
            for e in es:d[y[e,k]]=d.get(y[e,k],0)-lm[e,i]
            lp.eq(d,0);vec.append(v)
        s2.append(vec)
    qs2=[]
    for k in range(8):
        q=mass(lp,s2[k],f'qs2_{k}');lp.bounds[q]=(0.25,0.25);qs2.append(q)
    z2=[];q2=[]
    for p in range(4):
        A,B=s2[2*p],s2[2*p+1];z=[]
        if basepair_bottom:
            k0,k1=2*p,2*p+1
            E0=[e for e in range(8) if (e,k0) in y];E1=[e for e in range(8) if (e,k1) in y]
            rb=[];cbv=[]
            for bb in range(4):
                rv=lp.var(f'baseL_{p}_{bb}',0,1);d={rv:1}
                for e in E0:
                    if pat[e]==bb:d[y[e,k0]]=d.get(y[e,k0],0)-1
                lp.eq(d,0);rb.append(rv)
                cv=lp.var(f'baseR_{p}_{bb}',0,1);d={cv:1}
                for e in E1:
                    if pat[e]==bb:d[y[e,k1]]=d.get(y[e,k1],0)-1
                lp.eq(d,0);cbv.append(cv)
            H={}
            eligible=set(E0)|set(E1)
            for bb in range(4):
                for cc in range(4):
                    ub=1
                    if bb==cc and sum(1 for e in eligible if pat[e]==bb)<2:ub=0
                    H[bb,cc]=lp.var(f'Hbase_{p}_{bb}_{cc}',0,ub)
            for bb in range(4):
                d={rb[bb]:-1}
                for cc in range(4):d[H[bb,cc]]=1
                lp.eq(d,0)
            for cc in range(4):
                d={cbv[cc]:-1}
                for bb in range(4):d[H[bb,cc]]=1
                lp.eq(d,0)
            for i in range(4):
                cl,cu=cb(2);v=lp.var(f'z2_{p}_{i}',cl,cu);d={v:1}
                for bb in range(4):
                    for cc in range(4):d[H[bb,cc]]=d.get(H[bb,cc],0)-Pt[i,bb]*Pt[i,cc]
                lp.eq(d,0);z.append(v)
        elif exact_bottom:
            k0,k1=2*p,2*p+1
            E0=[e for e in range(8) if (e,k0) in y]
            E1=[e for e in range(8) if (e,k1) in y]
            H={}
            for e in E0:
                for f in E1:
                    if e==f: continue
                    H[e,f]=lp.var(f'h2_{p}_{e}_{f}',0,1)
            # RLT transportation marginals: H is a joint distribution for the two slots.
            for e in E0:
                d={y[e,k0]:-1}
                for f in E1:
                    if (e,f) in H:d[H[e,f]]=1
                lp.eq(d,0)
            for f in E1:
                d={y[f,k1]:-1}
                for e in E0:
                    if (e,f) in H:d[H[e,f]]=1
                lp.eq(d,0)
            for i in range(4):
                cl,cu=cb(2);v=lp.var(f'z2_{p}_{i}',cl,cu);d={v:1}
                for (e,f),h in H.items():d[h]=d.get(h,0)-lm[e,i]*lm[f,i]
                lp.eq(d,0);z.append(v)
        else:
            for i in range(4):
                lx,ux=lp.bounds[A[i]];ly,uy=lp.bounds[B[i]];cl,cu=cb(2)
                v=lp.var(f'z2_{p}_{i}',max(lx*ly,cl),min(ux*uy,cu));mcc(lp,v,A[i],B[i],lx,ux,ly,uy);z.append(v)
            if use_subset:add_subset_hulls(lp,A,B,z)
            if use_cross:
                ratio={}
                for i in range(4):
                    for j in range(i+1,4):
                        rr=Pt[i]/Pt[j];ratio[(i,j)]=(float(rr.min()),float(rr.max()))
                add_cross_product_rlt(lp,A,B,z,qs2[2*p],qs2[2*p+1],f'cross2_{p}',ratio,ratio)
        z2.append(z);q=mass(lp,z,f'q2_{p}');q2.append(q);l,u=mb(2);lp.bounds[q]=(l,u);lp.ge({q:1},l);lp.le({q:1},u)
        # prior parent<=selected child*sibling envelope
        _,cu=cb(2);_,qu=mb(2)
        for e in range(8):
            if p not in leaf_parents[e]:continue
            ks=[k for k,(pp,s) in enumerate(slots2) if pp==p and (e,k) in y]
            sib=[f for f in range(8) if f!=e and p in leaf_parents[f]]
            Us=np.array([max(lm[f,i] for f in sib) for i in range(4)])
            for i in range(4):
                target=Us[i]*lm[e,i];M=max(0,cu-target);d={z[i]:1}
                for k in ks:d[y[e,k]]=d.get(y[e,k],0)+M
                lp.le(d,target+M)
            targetq=.25*np.dot(Us,lm[e]);M=max(0,qu-targetq);d={q:1}
            for k in ks:d[y[e,k]]=d.get(y[e,k],0)+M
            lp.le(d,targetq+M)
    # count2 local transitions
    x2=[];qx2=[]
    for p in range(4):
        vec=[]
        for i in range(4):
            v=lp.var(f'x2_{p}_{i}',0,1);d={v:1}
            for j in range(4):d[z2[p][j]]=d.get(z2[p][j],0)-P2[p][i,j]
            lp.eq(d,0);vec.append(v)
        x2.append(vec);q=mass(lp,vec,f'qx2_{p}');qx2.append(q);lp.eq({q:1,q2[p]:-1},0)
        for i in range(4):
            for k in range(i+1,4):
                rr=P2[p][i]/P2[p][k];lp.ge({vec[i]:1,vec[k]:-rr.min()},0);lp.le({vec[i]:1,vec[k]:-rr.max()},0)
    bx2=[];dirfac=[[] for _ in range(4)]
    for p in range(4):
        bd=obbt(lp,x2[p]);bx2.append(bd)
        for i in range(4):lp.bounds[x2[p][i]]=bd[i]
        qlo,_=lp.solve({qx2[p]:1});qhi,_=lp.solve({qx2[p]:1},maximize=True);lp.bounds[qx2[p]]=(qlo,qhi)
        if use_dir:
            # Seven nontrivial +/- directions modulo global sign.
            dirs=[]
            for signs in itertools.product((-1,1),repeat=4):
                if signs[0] != 1 or all(v==1 for v in signs):continue
                dirs.append(signs)
            for c in dirs:
                obj={x2[p][i]:c[i] for i in range(4)}
                lo,_=lp.solve(obj);hi,_=lp.solve(obj,maximize=True)
                lp.ge(obj,lo);lp.le(obj,hi);dirfac[p].append((c,lo,hi))
    # count2 -> count4 routing
    y2={}
    for p in range(4):
        for k in range(4):y2[p,k]=lp.var(f'y2_{p}_{k}',0,1)
        lp.eq({y2[p,k]:1 for k in range(4)},1)
    for k in range(4):lp.eq({y2[p,k]:1 for p in range(4)},1)
    W={};G={};s4=[];qs4=[]
    for k in range(4):
        vec=[]
        for i in range(4):
            lb=min(bx2[p][i][0] for p in range(4));ub=max(bx2[p][i][1] for p in range(4))
            v=lp.var(f's4_{k}_{i}',lb,ub);d={v:1}
            for p in range(4):
                w=lp.var(f'w_{p}_{k}_{i}',0,ub);W[p,k,i]=w;routeprod_full(lp,w,y2[p,k],x2[p][i],*bx2[p][i]);d[w]=-1
            lp.eq(d,0);vec.append(v)
        s4.append(vec);qs=mass(lp,vec,f'qs4_{k}');qs4.append(qs)
        if use_route:
            for p in range(4):
                # Routed stationary mass: 1/4 sum_i w_i = y*q_x.
                lq,uq=lp.bounds[qx2[p]];g=lp.var(f'g_{p}_{k}',0,uq);G[p,k]=g;mcc(lp,g,y2[p,k],qx2[p],0,1,lq,uq)
                d={g:-1}
                for i in range(4):d[W[p,k,i]]=d.get(W[p,k,i],0)+.25
                lp.eq(d,0)
                # Lift the local transition ratio window to the routed fraction.
                for i in range(4):
                    for j in range(i+1,4):
                        rr=P2[p][i]/P2[p][j];rlo=float(rr.min());rhi=float(rr.max())
                        lp.ge({W[p,k,i]:1,W[p,k,j]:-rlo},0)
                        lp.le({W[p,k,i]:1,W[p,k,j]:-rhi},0)
                        # Local transition contracts the count-2 state window; lift that window through routing.
                        tau=0.5*float(np.abs(P2[p][i]-P2[p][j]).sum())
                        l2,u2=cb(2);D=tau*(u2-l2)
                        lp.le({W[p,k,i]:1,W[p,k,j]:-1,y2[p,k]:-D},0)
                        lp.le({W[p,k,j]:1,W[p,k,i]:-1,y2[p,k]:-D},0)
                if use_dir:
                    for c,lo,hi in dirfac[p]:
                        d={y2[p,k]:-lo}
                        for i in range(4):d[W[p,k,i]]=d.get(W[p,k,i],0)+c[i]
                        lp.ge(d,0)
                        d={y2[p,k]:-hi}
                        for i in range(4):d[W[p,k,i]]=d.get(W[p,k,i],0)+c[i]
                        lp.le(d,0)
    for p in range(4):
        for i in range(4):
            d={x2[p][i]:-1}
            for k in range(4):d[W[p,k,i]]=1
            lp.eq(d,0)
        if use_route:
            d={qx2[p]:-1}
            for k in range(4):d[G[p,k]]=1
            lp.eq(d,0)
    if use_route or use_subset or use_cross:
        for k in range(4):
            bd=obbt(lp,s4[k])
            for i in range(4):lp.bounds[s4[k][i]]=bd[i]
            qlo,_=lp.solve({qs4[k]:1});qhi,_=lp.solve({qs4[k]:1},maximize=True);lp.bounds[qs4[k]]=(qlo,qhi)
    # count4 products
    z4=[];q4=[]
    for q in range(2):
        A,B=s4[2*q],s4[2*q+1];qa,qb=qs4[2*q],qs4[2*q+1];z=[]
        for i in range(4):
            lx,ux=lp.bounds[A[i]];ly,uy=lp.bounds[B[i]];cl,cu=cb(4);v=lp.var(f'z4_{q}_{i}',max(lx*ly,cl),min(ux*uy,cu));mcc(lp,v,A[i],B[i],lx,ux,ly,uy);z.append(v)
        if use_subset:add_subset_hulls(lp,A,B,z)
        if upper_pair_rlt:
            k0,k1=2*q,2*q+1;H={};AA={};BB={};TT={}
            for p0 in range(4):
                for r0 in range(4):
                    if p0==r0:continue
                    h=lp.var(f'Hup_{q}_{p0}_{r0}',0,1);H[p0,r0]=h
                    for i in range(4):
                        xp=x2[p0][i];xr=x2[r0][i];lp0,up0=bx2[p0][i];lr0,ur0=bx2[r0][i]
                        aa=lp.var(f'Aup_{q}_{p0}_{r0}_{i}',0,up0);bb=lp.var(f'Bup_{q}_{p0}_{r0}_{i}',0,ur0)
                        routeprod_full(lp,aa,h,xp,lp0,up0);routeprod_full(lp,bb,h,xr,lr0,ur0)
                        tt=lp.var(f'Tup_{q}_{p0}_{r0}_{i}',0,up0*ur0)
                        mcc(lp,tt,aa,xr,0,up0,lr0,ur0)
                        mcc(lp,tt,bb,xp,0,ur0,lp0,up0)
                        AA[p0,r0,i]=aa;BB[p0,r0,i]=bb;TT[p0,r0,i]=tt
            # H marginals are exactly the two slot-routing marginals.
            for p0 in range(4):
                d={y2[p0,k0]:-1}
                for r0 in range(4):
                    if p0!=r0:d[H[p0,r0]]=1
                lp.eq(d,0)
            for r0 in range(4):
                d={y2[r0,k1]:-1}
                for p0 in range(4):
                    if p0!=r0:d[H[p0,r0]]=1
                lp.eq(d,0)
            # Pair-routed copies aggregate back to the existing routed messages.
            for p0 in range(4):
                for i in range(4):
                    d={W[p0,k0,i]:-1}
                    for r0 in range(4):
                        if p0!=r0:d[AA[p0,r0,i]]=1
                    lp.eq(d,0)
            for r0 in range(4):
                for i in range(4):
                    d={W[r0,k1,i]:-1}
                    for p0 in range(4):
                        if p0!=r0:d[BB[p0,r0,i]]=1
                    lp.eq(d,0)
            for i in range(4):
                d={z[i]:-1}
                for p0 in range(4):
                    for r0 in range(4):
                        if p0!=r0:d[TT[p0,r0,i]]=1
                lp.eq(d,0)
        z4.append(z);qp=mass(lp,z,f'q4_{q}');q4.append(qp);l,u=mb(4);lp.bounds[qp]=(l,u);lp.ge({qp:1},l);lp.le({qp:1},u)
        lp.le({qp:1,qa:-1},0);lp.le({qp:1,qb:-1},0)
        UA=max(lp.bounds[v][1] for v in A);UB=max(lp.bounds[v][1] for v in B);lp.le({qp:1,qa:-UB},0);lp.le({qp:1,qb:-UA},0)
        # Conditional parent <= selected count-2 child times best possible complementary count-2 envelope.
        _,qu4=mb(4);_,cu4=cb(4)
        for p in range(4):
            ks=[2*q,2*q+1]; others=[r for r in range(4) if r!=p]
            Usib=np.array([max(bx2[r][i][1] for r in others) for i in range(4)])
            rhs_lb=sum(0.25*Usib[i]*bx2[p][i][0] for i in range(4))
            M=max(0,qu4-rhs_lb);d={qp:1}
            for i in range(4):d[x2[p][i]]=d.get(x2[p][i],0)-0.25*Usib[i]
            for k in ks:d[y2[p,k]]=d.get(y2[p,k],0)+M
            lp.le(d,M)
            for i in range(4):
                M=max(0,cu4-Usib[i]*bx2[p][i][0]);d={z[i]:1,x2[p][i]:-Usib[i]}
                for k in ks:d[y2[p,k]]=d.get(y2[p,k],0)+M
                lp.le(d,M)
        if use_cross:
            ratio={}
            for i in range(4):
                for j in range(i+1,4):
                    lows=[];highs=[]
                    for P in P2:
                        rr=P[i]/P[j];lows.append(float(rr.min()));highs.append(float(rr.max()))
                    ratio[(i,j)]=(min(lows),max(highs))
            add_cross_product_rlt(lp,A,B,z,qa,qb,f'cross4_{q}',ratio,ratio)
    # count4 transitions
    x4=[]
    for q in range(2):
        vec=[]
        for i in range(4):
            v=lp.var(f'x4_{q}_{i}',0,1);d={v:1}
            for j in range(4):d[z4[q][j]]=d.get(z4[q][j],0)-P4[q][i,j]
            lp.eq(d,0);vec.append(v)
        x4.append(vec);qx=mass(lp,vec,f'qx4_{q}');lp.eq({qx:1,q4[q]:-1},0)
        for i in range(4):
            for k in range(i+1,4):
                rr=P4[q][i]/P4[q][k];lp.ge({vec[i]:1,vec[k]:-rr.min()},0);lp.le({vec[i]:1,vec[k]:-rr.max()},0)
        bd=obbt(lp,vec)
        for i in range(4):lp.bounds[vec[i]]=bd[i]
    # root
    z8=[]
    for i in range(4):
        lx,ux=lp.bounds[x4[0][i]];ly,uy=lp.bounds[x4[1][i]];cl,cu=cb(8);v=lp.var(f'z8_{i}',max(lx*ly,cl),min(ux*uy,cu));mcc(lp,v,x4[0][i],x4[1][i],lx,ux,ly,uy);z8.append(v)
    if use_subset:add_subset_hulls(lp,x4[0],x4[1],z8)
    q8=mass(lp,z8,'q8');l,u=mb(8);lp.bounds[q8]=(l,u);lp.ge({q8:1},l);lp.le({q8:1},u)
    lp.le({q8:1,q4[0]:-1},0);lp.le({q8:1,q4[1]:-1},0)
    U0=max(lp.bounds[v][1] for v in x4[0]);U1=max(lp.bounds[v][1] for v in x4[1]);lp.le({q8:1,q4[0]:-U1},0);lp.le({q8:1,q4[1]:-U0},0)
    if use_cross:
        r0={};r1={}
        for i in range(4):
            for j in range(i+1,4):
                rr=P4[0][i]/P4[0][j];r0[(i,j)]=(float(rr.min()),float(rr.max()))
                rr=P4[1][i]/P4[1][j];r1[(i,j)]=(float(rr.min()),float(rr.max()))
        add_cross_product_rlt(lp,x4[0],x4[1],z8,q4[0],q4[1],'cross8',r0,r1)
    return lp.solve({q8:1},maximize=True)[0]

patterns={
 'AAAACCCC':(0,0,0,0,1,1,1,1),
 'AACCGGTT':(0,0,1,1,2,2,3,3),
 'ACGTACGT':(0,1,2,3,0,1,2,3),
}
rows=[]
for name,pat in patterns.items():
    ex=exact_best(pat);edge=b.build(pat,'edge')
    basepair=build(pat,True,True,True,False,False,True,False)
    upper=build(pat,True,True,True,False,False,True,True)
    print(name,ex,edge,basepair,upper,flush=True)
    rows.append({'pattern':name,'exact':ex,'prior edge':edge,'base-pair+state RLT':basepair,'+ upper pair-coupled RLT':upper,'prior/exact':edge/ex,'final/exact':upper/ex,'residual gap removed':(edge-upper)/(edge-ex)})
pd.DataFrame(rows).to_csv('/mnt/data/heterogeneous_upper_pair_rlt.csv',index=False)
print(pd.DataFrame(rows).to_string(index=False))
